### ISSUE TITLE
Webpack hangs on commands + does not autoreload

### ISSUE THREAD

**Issue by sfrostenson** [The-Politico/generator-politico-graphics#14]
When running commands like `gulp archie` or `gulp spreadsheet`, the command is executed, but is not exited out, creating hanging commands. Additionally, when changes are made to the src folder and saved, the browser is not automatically refreshed.

**Comment by TylerFisher** [comment]
I believe I have a fix (though crude) for the hanging commands. Autoreloading for things that aren't JS and CSS is... harder than it should be. Because we handle JS and CSS through Webpack, which has a hot reloader, and HTML, Archie JSON, etc. through Express/Nunjucks, which does not have a hot reloader, there's not a great solution here.
